In [51]:
import pandas as pd 
print("Welcome to pau-sims")
class sims():
     
    
    
    #attributes
    def __innit__(self,name,level,matric,department):
        
        self.name = []
        self.matric = []
        self.dept = []
        self.level = []
                   


    def folder(self):
                    
        folder = {}
        folder["student Name"] = self.name
        folder["level"] = self.level
        folder["matric"] = self.matric
        folder["department"] = self.department

        df = pd.DataFrame(folder)
        df.to_csv("Sims.csv", index_label= "No", na_rep = "M/A")
        print('file has been created successfully')


        def inps(self):
            
        while True:
        name = input("do please enter your name")
        self.name.append(name)
        matric = input("do please  enter your matric number")
        self.matric.append(matric)
        department = input("do please enter your department")
        self.department.append(department)
        level = input("do please enter your level")
        self.level.append(level)

         if not self.request():
                return False
            

    df request(self):
        
        global request
         request = input("input x to put down details for another student.Input  a to end the program and make a csv file")
            if request.lower() == "a":
                 print("Thank you for deciding to make use of this program")
                     return False
                     elif request.lower() == "x":
                            return True

IndentationError: expected an indented block (<ipython-input-51-07d52d8223fc>, line 32)

In [52]:
import pandas as pd

details = {"Company Name": ["Enron Corporation",'Anderson industries',"GK Jones","Mica Industries","Dune Industries"],
           "Date of Establishment":["1987","1936","2001","1996","2008"],
           "Company's shares":["1,000,000","1,500,000","3,000,000","250,000","800,000"],
           "Company's liability":["200,000","500,000","1,500,000","50,000","300,000"],
           "Percentage Leverage":["80%","66.7%","50%","80%","62.5%"]}
    #Making the excel file
df = pd.DataFrame(details)
    

    #Saving the file
df.to_csv("Company.csv")

df

,Company Name,Date of Establishment,Company's shares,Company's liability,Percentage Leverage
0,Enron Corporation,1987,"1,000,000","200,000",80%
1,Anderson industries,1936,"1,500,000","500,000",66.7%
2,GK Jones,2001,"3,000,000","1,500,000",50%
3,Mica Industries,1996,"250,000","50,000",80%
4,Dune Industries,2008,"800,000","300,000",62.5%